[app]
title = Archäologie
package.name = archaeologie
package.domain = org.example
source.dir = .
source.include_exts = py
version = 1.0
entrypoint = main.py
orientation = portrait
requirements = python3,kivy,pyjnius,android,pillow,bleak,asyncio
android.permissions = BLUETOOTH,BLUETOOTH_ADMIN,BLUETOOTH_SCAN,BLUETOOTH_CONNECT,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION
fullscreen = 0
android.api = 33
android.minapi = 26
android.sdk = 33
android.ndk = 25
android.archs = arm64-v8a
android.logcat_filters = *:S python:D
warn_on_root = 1
